package ru.aloyaloya.design_system.theme

import androidx.compose.ui.graphics.Color

val LightBackground = Color(0xFFFBF8F5)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceMuted = Color(0xFFF4EFEA)
val LightOutline = Color(0xFFF0E9E3)
val LightOutlineStrong = Color(0xFFE4DAD2)
val LightTextPrimary = Color(0xFF241F1C)
val LightTextSecondary = Color(0xFF9A918B)
val LightTextTertiary = Color(0xFFB3A79F)
val LightTextQuaternary = Color(0xFFCFC5BD)
val LightAccent = Color(0xFFFF7A5A)
val LightAccentContainer = Color(0xFFFFEDE8)
val LightOnAccent = Color(0xFFFFFFFF)
val LightDanger = Color(0xFFD8483A)
val LightDangerContainer = Color(0xFFFDE7E3)

val DarkBackground = Color(0xFF1B1714)
val DarkSurface = Color(0xFF241F1B)
val DarkSurfaceMuted = Color(0xFF2E2822)
val DarkOutline = Color(0xFF322B25)
val DarkOutlineStrong = Color(0xFF3E362F)
val DarkTextPrimary = Color(0xFFF6F0EA)
val DarkTextSecondary = Color(0xFF9C9088)
val DarkTextTertiary = Color(0xFF7C726B)
val DarkTextQuaternary = Color(0xFF5A524B)
val DarkAccent = Color(0xFFFF7A5A)
val DarkAccentContainer = Color(0xFF3A241E)
val DarkOnAccent = Color(0xFF1B1714)
val DarkDanger = Color(0xFFFF6B57)
val DarkDangerContainer = Color(0xFF3A211C)

val LightHappySolid = Color(0xFFFFD9A8)
val LightHappySoft = Color(0xFFFFF3E2)
val LightTenderSolid = Color(0xFFFFC2C7)
val LightTenderSoft = Color(0xFFFFE6E8)
val LightSurprisedSolid = Color(0xFFDCD3F5)
val LightSurprisedSoft = Color(0xFFEFEAFB)
val LightCalmSolid = Color(0xFFBFE3D3)
val LightCalmSoft = Color(0xFFE4F2EC)
val LightSadSolid = Color(0xFFC9DDF2)
val LightSadSoft = Color(0xFFE6EFFA)
val LightAngrySolid = Color(0xFFF5C4B6)
val LightAngrySoft = Color(0xFFFBE6E1)

val DarkHappySolid = Color(0xFF7A5A2E)
val DarkHappySoft = Color(0xFF3A2E1E)
val DarkTenderSolid = Color(0xFF8E4E52)
val DarkTenderSoft = Color(0xFF3B2427)
val DarkSurprisedSolid = Color(0xFF5A4E86)
val DarkSurprisedSoft = Color(0xFF2B2740)
val DarkCalmSolid = Color(0xFF3B6B5A)
val DarkCalmSoft = Color(0xFF1F2E29)
val DarkSadSolid = Color(0xFF3F5C7D)
val DarkSadSoft = Color(0xFF1E2833)
val DarkAngrySolid = Color(0xFF8A4B3A)
val DarkAngrySoft = Color(0xFF33221D)
